# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeGCD <- function(a, b) {
    .Call('RcppWavelet_computeGCD', PACKAGE = 'RcppWavelet', a, b)
}

computeLCM <- function(a, b) {
    .Call('RcppWavelet_computeLCM', PACKAGE = 'RcppWavelet', a, b)
}

rcpparma_hello_world <- function() {
    .Call('RcppWavelet_rcpparma_hello_world', PACKAGE = 'RcppWavelet')
}

rcpparma_outerproduct <- function(x) {
    .Call('RcppWavelet_rcpparma_outerproduct', PACKAGE = 'RcppWavelet', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('RcppWavelet_rcpparma_innerproduct', PACKAGE = 'RcppWavelet', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('RcppWavelet_rcpparma_bothproducts', PACKAGE = 'RcppWavelet', x)
}

RcppWaveletTest <- function(x, bands_per_octave = 8, frequency_min = 0.001953125, frequency_max = 0.5, samplerate_hz = 1) {
    .Call('RcppWavelet_RcppWaveletTest', PACKAGE = 'RcppWavelet', x, bands_per_octave, frequency_min, frequency_max, samplerate_hz)
}

