# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

analyze <- function(x, bands_per_octave = 8, frequency_min = 0.001953125, frequency_max = 0.5, samplerate_hz = 1, mother_wavelet = "MORLET", morlet_carrier = 5, paul_order = 2L, cores = 1L, optimisation = "NONE") {
    .Call('_RcppWavelet_analyze', PACKAGE = 'RcppWavelet', x, bands_per_octave, frequency_min, frequency_max, samplerate_hz, mother_wavelet, morlet_carrier, paul_order, cores, optimisation)
}

